--
-- TOC entry 184 (class 1259 OID 18968)
-- Name: geo_place; Type: TABLE; Schema: public; Owner: postgres; Tablespace:
--
CREATE USER postgres;

CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION dblink;


--
-- TOC entry 3071 (class 1259 OID 18977)
-- Name: geo_palce_cog_type_index; Type: INDEX; Schema: public; Owner: postgres; Tablespace:
--

-- Dumped from database version 11.2
-- Dumped by pg_dump version 11.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;


--
-- Name: listings; Type: TABLE; Schema: public; Owner: listingapi
--

CREATE TABLE public.listings (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price integer NOT NULL,
    surface_area_m2 integer NOT NULL,
    rooms_count integer NOT NULL,
    bedrooms_count integer NOT NULL,
    building_type text NULL,
    contact_phone_number text NULL,
    created_date timestamp without time zone NOT NULL,
    updated_date timestamp without time zone NOT NULL,
    name text NULL,
    description text NULL,
    price_date_posted timestamp without time zone NOT NULL,
    street_address text NULL,
    postal_code text NULL,
    city text NULL,
    country text NULL,
    CONSTRAINT "PK_listings" PRIMARY KEY (id)
);


ALTER TABLE public.listings OWNER TO listingapi;


--
-- PostgreSQL database dump complete
--
