version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18
    volumes:
      - ../../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      PGHOST: localhost
      PGDATABASE: listing
      PGUSER: listing
      PGPASSWORD: listing

  db:
    image: "mdillon/postgis:11-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: listing
      POSTGRES_USER: listing
      POSTGRES_PASSWORD: listing

volumes:
  postgres-data:
